spring:
  config:
    activate:
      on-profile: dev
    import: dev-secret.yml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${secret.datasource.url}
    username: ${secret.datasource.username}
    password: ${secret.datasource.password}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${secret.kakao.client_id}
            client-secret: ${secret.kakao.client_secret}
            redirect-uri: ${secret.kakao.redirect_uri}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# [수정 4] JWT 관련 설정도 환경변수로 변경
jwt:
  secret-key: ${secret.jwt.secret-key}
  access-token-expiration: ${secret.jwt.access-token-expiration}
  refresh-token-expiration: ${secret.jwt.refresh-token-expiration}

kakao:
  token-info-url: https://kauth.kakao.com/oauth/tokeninfo