name: Deploy to EC2 with Docker

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # github repo에는 dev-secret.yml 파일이 안올라가니
      # github action에서 미리 환경변수에 입력해 놓은 DEV_SECRET_YML을 가져와서
      # 프로젝트 "/src/main/resources" 경로에 dev-secret.yml 파일을 만든다.
      - name: Create dev-secret.yml
        shell: bash
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.DEV_SECRET_YML }}" > ./src/main/resources/dev-secret.yml
          ls -al ./src/main/resources

      # dev-secret.yml 파일이 생성된 상태에서 프로젝트를 build 하여
      # JAR 파일 생성
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      # Docker Hub 접속
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # JAR 파일을 Dockerfile에 때하 docker image로 만들고
      # docker hub에 push
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weterview-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/weterview-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1. [중요] 새 이미지를 '먼저' 받는다. (서버가 살아있는 상태에서 진행됨)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/weterview-server:latest

            # 2. 기존 컨테이너 중지 및 삭제 (다운타임 시작 - 최소화)
            sudo docker stop weterview-server || true
            sudo docker rm weterview-server || true

            # 3. 새 컨테이너 실행 (다운타임 종료)
            # --network host 등 필요한 네트워크 설정이 있다면 추가
            sudo docker run -d --name weterview-server -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/weterview-server:latest

            # 4. 미사용 이미지 정리 (공간 확보)
            sudo docker image prune -f